# Generated by Django 4.2.1 on 2025-04-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImageModel',
        ),
        migrations.DeleteModel(
            name='CustomRoleModel',
        ),
        migrations.DeleteModel(
            name='LocalMemoryModel',
        ),
        migrations.DeleteModel(
            name='PortalUser',
        ),
        migrations.DeleteModel(
            name='RolePackageModel',
        ),
        migrations.DeleteModel(
            name='SysConfigModel',
        ),
        migrations.DeleteModel(
            name='VrmModel',
        ),
    ]
