# Generated by Django 4.2.1 on 2025-04-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_comment='用户ID')),
                ('role_id', models.IntegerField(db_comment='角色ID')),
                ('emotion_state', models.TextField(db_comment='情感状态JSON')),
                ('last_update', models.DateTimeField(auto_now=True, db_comment='最后更新时间')),
            ],
            options={
                'db_table': 'emotion_state',
                'db_table_comment': '情感状态存储表',
                'unique_together': {('user_id', 'role_id')},
            },
        ),
    ]
