# Generated by Django 4.2.1 on 2025-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_emotionstatemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionStateModel',
        ),
        migrations.AlterField(
            model_name='customrolemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
